// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contracts.sql

package sqlc

import (
	"context"
)

const deleteContractRequirements = `-- name: DeleteContractRequirements :exec
DELETE FROM requirements
WHERE contract_id = $1
`

func (q *Queries) DeleteContractRequirements(ctx context.Context, contractID string) error {
	_, err := q.db.Exec(ctx, deleteContractRequirements, contractID)
	return err
}

const getContract = `-- name: GetContract :one
SELECT id, primitive_id, version, summary
FROM contracts
WHERE id = $1
`

func (q *Queries) GetContract(ctx context.Context, id string) (Contract, error) {
	row := q.db.QueryRow(ctx, getContract, id)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.PrimitiveID,
		&i.Version,
		&i.Summary,
	)
	return i, err
}

const insertRequirement = `-- name: InsertRequirement :exec
INSERT INTO requirements (contract_id, requirement_id, position, description, kind, required)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRequirementParams struct {
	ContractID    string
	RequirementID string
	Position      int32
	Description   string
	Kind          string
	Required      bool
}

func (q *Queries) InsertRequirement(ctx context.Context, arg InsertRequirementParams) error {
	_, err := q.db.Exec(ctx, insertRequirement,
		arg.ContractID,
		arg.RequirementID,
		arg.Position,
		arg.Description,
		arg.Kind,
		arg.Required,
	)
	return err
}

const listRequirementsByContract = `-- name: ListRequirementsByContract :many
SELECT contract_id, requirement_id, position, description, kind, required
FROM requirements
WHERE contract_id = $1
ORDER BY position
`

func (q *Queries) ListRequirementsByContract(ctx context.Context, contractID string) ([]Requirement, error) {
	rows, err := q.db.Query(ctx, listRequirementsByContract, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Requirement{}
	for rows.Next() {
		var i Requirement
		if err := rows.Scan(
			&i.ContractID,
			&i.RequirementID,
			&i.Position,
			&i.Description,
			&i.Kind,
			&i.Required,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContract = `-- name: UpsertContract :one
INSERT INTO contracts (id, primitive_id, version, summary)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET primitive_id = EXCLUDED.primitive_id,
    version      = EXCLUDED.version,
    summary      = EXCLUDED.summary
RETURNING id, primitive_id, version, summary
`

type UpsertContractParams struct {
	ID          string
	PrimitiveID string
	Version     string
	Summary     string
}

func (q *Queries) UpsertContract(ctx context.Context, arg UpsertContractParams) (Contract, error) {
	row := q.db.QueryRow(ctx, upsertContract,
		arg.ID,
		arg.PrimitiveID,
		arg.Version,
		arg.Summary,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.PrimitiveID,
		&i.Version,
		&i.Summary,
	)
	return i, err
}
