// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEvidence = `-- name: GetEvidence :one
SELECT id, subject_id, kind, claim, result, source_url, source_revision, source_path, source_license, observed_at, applies_to, methodology, artifact
FROM evidence
WHERE id = $1
`

func (q *Queries) GetEvidence(ctx context.Context, id string) (Evidence, error) {
	row := q.db.QueryRow(ctx, getEvidence, id)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Kind,
		&i.Claim,
		&i.Result,
		&i.SourceUrl,
		&i.SourceRevision,
		&i.SourcePath,
		&i.SourceLicense,
		&i.ObservedAt,
		&i.AppliesTo,
		&i.Methodology,
		&i.Artifact,
	)
	return i, err
}

const insertEvidence = `-- name: InsertEvidence :one
INSERT INTO evidence (id, subject_id, kind, claim, result, source_url, source_revision, source_path, source_license, observed_at, applies_to, methodology, artifact)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, subject_id, kind, claim, result, source_url, source_revision, source_path, source_license, observed_at, applies_to, methodology, artifact
`

type InsertEvidenceParams struct {
	ID             string
	SubjectID      string
	Kind           string
	Claim          string
	Result         string
	SourceUrl      string
	SourceRevision string
	SourcePath     string
	SourceLicense  string
	ObservedAt     pgtype.Timestamptz
	AppliesTo      string
	Methodology    string
	Artifact       string
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, insertEvidence,
		arg.ID,
		arg.SubjectID,
		arg.Kind,
		arg.Claim,
		arg.Result,
		arg.SourceUrl,
		arg.SourceRevision,
		arg.SourcePath,
		arg.SourceLicense,
		arg.ObservedAt,
		arg.AppliesTo,
		arg.Methodology,
		arg.Artifact,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Kind,
		&i.Claim,
		&i.Result,
		&i.SourceUrl,
		&i.SourceRevision,
		&i.SourcePath,
		&i.SourceLicense,
		&i.ObservedAt,
		&i.AppliesTo,
		&i.Methodology,
		&i.Artifact,
	)
	return i, err
}

const listEvidenceBySubject = `-- name: ListEvidenceBySubject :many
SELECT id, subject_id, kind, claim, result, source_url, source_revision, source_path, source_license, observed_at, applies_to, methodology, artifact
FROM evidence
WHERE subject_id = $1
ORDER BY observed_at, id
`

func (q *Queries) ListEvidenceBySubject(ctx context.Context, subjectID string) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Evidence{}
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Kind,
			&i.Claim,
			&i.Result,
			&i.SourceUrl,
			&i.SourceRevision,
			&i.SourcePath,
			&i.SourceLicense,
			&i.ObservedAt,
			&i.AppliesTo,
			&i.Methodology,
			&i.Artifact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidencePage = `-- name: ListEvidencePage :many
SELECT id, subject_id, kind, claim, result, source_url, source_revision, source_path, source_license, observed_at, applies_to, methodology, artifact
FROM evidence
WHERE subject_id = $1
  AND (observed_at, id) > ($2::timestamptz, $3::text)
ORDER BY observed_at, id
LIMIT $4::int
`

type ListEvidencePageParams struct {
	SubjectID       string
	AfterObservedAt pgtype.Timestamptz
	AfterID         string
	PageLimit       int32
}

func (q *Queries) ListEvidencePage(ctx context.Context, arg ListEvidencePageParams) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidencePage,
		arg.SubjectID,
		arg.AfterObservedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Evidence{}
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Kind,
			&i.Claim,
			&i.Result,
			&i.SourceUrl,
			&i.SourceRevision,
			&i.SourcePath,
			&i.SourceLicense,
			&i.ObservedAt,
			&i.AppliesTo,
			&i.Methodology,
			&i.Artifact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
