// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertResolutionFeedback = `-- name: InsertResolutionFeedback :one
INSERT INTO resolution_feedback (resolution_id, kind, note, recorded_at)
VALUES ($1, $2, $3, $4)
RETURNING id, resolution_id, kind, note, recorded_at
`

type InsertResolutionFeedbackParams struct {
	ResolutionID int64
	Kind         string
	Note         string
	RecordedAt   pgtype.Timestamptz
}

func (q *Queries) InsertResolutionFeedback(ctx context.Context, arg InsertResolutionFeedbackParams) (ResolutionFeedback, error) {
	row := q.db.QueryRow(ctx, insertResolutionFeedback,
		arg.ResolutionID,
		arg.Kind,
		arg.Note,
		arg.RecordedAt,
	)
	var i ResolutionFeedback
	err := row.Scan(
		&i.ID,
		&i.ResolutionID,
		&i.Kind,
		&i.Note,
		&i.RecordedAt,
	)
	return i, err
}

const listResolutionFeedback = `-- name: ListResolutionFeedback :many
SELECT id, resolution_id, kind, note, recorded_at
FROM resolution_feedback
WHERE resolution_id = $1
ORDER BY recorded_at, id
LIMIT $2
`

type ListResolutionFeedbackParams struct {
	ResolutionID int64
	Limit        int32
}

func (q *Queries) ListResolutionFeedback(ctx context.Context, arg ListResolutionFeedbackParams) ([]ResolutionFeedback, error) {
	rows, err := q.db.Query(ctx, listResolutionFeedback, arg.ResolutionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolutionFeedback{}
	for rows.Next() {
		var i ResolutionFeedback
		if err := rows.Scan(
			&i.ID,
			&i.ResolutionID,
			&i.Kind,
			&i.Note,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
