// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contract struct {
	ID          string
	PrimitiveID string
	Version     string
	Summary     string
}

type Evidence struct {
	ID             string
	SubjectID      string
	Kind           string
	Claim          string
	Result         string
	SourceUrl      string
	SourceRevision string
	SourcePath     string
	SourceLicense  string
	ObservedAt     pgtype.Timestamptz
	AppliesTo      string
	Methodology    string
	Artifact       string
}

type Primitive struct {
	ID          string
	Name        string
	Description string
	Tags        []string
	ContractID  string
}

type Project struct {
	ID            string
	Name          string
	SourceKind    string
	SourceLocator string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ProjectContext struct {
	Hash          string
	ProjectID     string
	FingerprintID int64
	ContextJson   []byte
	CreatedAt     pgtype.Timestamptz
}

type ProjectFingerprint struct {
	ID                int64
	ProjectID         string
	SchemaVersion     int32
	FingerprintSha256 string
	FingerprintJson   []byte
	SourceRevision    string
	ObservedAt        pgtype.Timestamptz
}

type ProjectPreference struct {
	ID                 int64
	ProjectID          string
	Kind               string
	PrimitiveID        string
	CandidateID        string
	TextValue          string
	IntValue           *int32
	SourceReason       string
	SourceResolutionID *int64
	RecordedAt         pgtype.Timestamptz
	ForgottenAt        pgtype.Timestamptz
}

type Rejection struct {
	ResolutionID int64
	Position     int32
	SpecimenID   string
	Reasons      []string
}

type Requirement struct {
	ContractID    string
	RequirementID string
	Position      int32
	Description   string
	Kind          string
	Required      bool
}

type Resolution struct {
	ID                 int64
	PrimitiveID        string
	ContractID         string
	Outcome            string
	SpecimenID         *string
	Reasons            []string
	Unknowns           []string
	EvidenceIds        []string
	ResolvedAt         pgtype.Timestamptz
	PolicyID           string
	ProjectID          *string
	ProjectContextHash *string
}

type ResolutionFeedback struct {
	ID           int64
	ResolutionID int64
	Kind         string
	Note         string
	RecordedAt   pgtype.Timestamptz
}

type Specimen struct {
	ID             string
	PrimitiveID    string
	Name           string
	SourceUrl      string
	SourceRevision string
	SourcePath     string
	SourceLicense  string
	ReuseModes     []string
}
