// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: primitives.sql

package sqlc

import (
	"context"
)

const getPrimitive = `-- name: GetPrimitive :one
SELECT id, name, description, tags, contract_id
FROM primitives
WHERE id = $1
`

func (q *Queries) GetPrimitive(ctx context.Context, id string) (Primitive, error) {
	row := q.db.QueryRow(ctx, getPrimitive, id)
	var i Primitive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.ContractID,
	)
	return i, err
}

const upsertPrimitive = `-- name: UpsertPrimitive :one
INSERT INTO primitives (id, name, description, tags, contract_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
SET name        = EXCLUDED.name,
    description = EXCLUDED.description,
    tags        = EXCLUDED.tags,
    contract_id = EXCLUDED.contract_id
RETURNING id, name, description, tags, contract_id
`

type UpsertPrimitiveParams struct {
	ID          string
	Name        string
	Description string
	Tags        []string
	ContractID  string
}

func (q *Queries) UpsertPrimitive(ctx context.Context, arg UpsertPrimitiveParams) (Primitive, error) {
	row := q.db.QueryRow(ctx, upsertPrimitive,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.ContractID,
	)
	var i Primitive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.ContractID,
	)
	return i, err
}
