// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const forgetProjectPreference = `-- name: ForgetProjectPreference :exec
UPDATE project_preferences
SET forgotten_at = $3
WHERE id = $1
  AND project_id = $2
  AND forgotten_at IS NULL
`

type ForgetProjectPreferenceParams struct {
	ID          int64
	ProjectID   string
	ForgottenAt pgtype.Timestamptz
}

func (q *Queries) ForgetProjectPreference(ctx context.Context, arg ForgetProjectPreferenceParams) error {
	_, err := q.db.Exec(ctx, forgetProjectPreference, arg.ID, arg.ProjectID, arg.ForgottenAt)
	return err
}

const getLatestProjectFingerprint = `-- name: GetLatestProjectFingerprint :one
SELECT id, project_id, schema_version, fingerprint_sha256, fingerprint_json, source_revision, observed_at
FROM project_fingerprints
WHERE project_id = $1
ORDER BY observed_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestProjectFingerprint(ctx context.Context, projectID string) (ProjectFingerprint, error) {
	row := q.db.QueryRow(ctx, getLatestProjectFingerprint, projectID)
	var i ProjectFingerprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SchemaVersion,
		&i.FingerprintSha256,
		&i.FingerprintJson,
		&i.SourceRevision,
		&i.ObservedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, source_kind, source_locator, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceKind,
		&i.SourceLocator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectContext = `-- name: GetProjectContext :one
SELECT hash, project_id, fingerprint_id, context_json, created_at
FROM project_contexts
WHERE hash = $1
`

func (q *Queries) GetProjectContext(ctx context.Context, hash string) (ProjectContext, error) {
	row := q.db.QueryRow(ctx, getProjectContext, hash)
	var i ProjectContext
	err := row.Scan(
		&i.Hash,
		&i.ProjectID,
		&i.FingerprintID,
		&i.ContextJson,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectFingerprintByHash = `-- name: GetProjectFingerprintByHash :one
SELECT id, project_id, schema_version, fingerprint_sha256, fingerprint_json, source_revision, observed_at
FROM project_fingerprints
WHERE project_id = $1
  AND fingerprint_sha256 = $2
`

type GetProjectFingerprintByHashParams struct {
	ProjectID         string
	FingerprintSha256 string
}

func (q *Queries) GetProjectFingerprintByHash(ctx context.Context, arg GetProjectFingerprintByHashParams) (ProjectFingerprint, error) {
	row := q.db.QueryRow(ctx, getProjectFingerprintByHash, arg.ProjectID, arg.FingerprintSha256)
	var i ProjectFingerprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SchemaVersion,
		&i.FingerprintSha256,
		&i.FingerprintJson,
		&i.SourceRevision,
		&i.ObservedAt,
	)
	return i, err
}

const getProjectPreference = `-- name: GetProjectPreference :one
SELECT id, project_id, kind, primitive_id, candidate_id, text_value, int_value, source_reason, source_resolution_id, recorded_at, forgotten_at
FROM project_preferences
WHERE id = $1
  AND project_id = $2
`

type GetProjectPreferenceParams struct {
	ID        int64
	ProjectID string
}

func (q *Queries) GetProjectPreference(ctx context.Context, arg GetProjectPreferenceParams) (ProjectPreference, error) {
	row := q.db.QueryRow(ctx, getProjectPreference, arg.ID, arg.ProjectID)
	var i ProjectPreference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.PrimitiveID,
		&i.CandidateID,
		&i.TextValue,
		&i.IntValue,
		&i.SourceReason,
		&i.SourceResolutionID,
		&i.RecordedAt,
		&i.ForgottenAt,
	)
	return i, err
}

const insertProjectFingerprint = `-- name: InsertProjectFingerprint :one
INSERT INTO project_fingerprints
    (project_id, schema_version, fingerprint_sha256, fingerprint_json, source_revision, observed_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, schema_version, fingerprint_sha256, fingerprint_json, source_revision, observed_at
`

type InsertProjectFingerprintParams struct {
	ProjectID         string
	SchemaVersion     int32
	FingerprintSha256 string
	FingerprintJson   []byte
	SourceRevision    string
	ObservedAt        pgtype.Timestamptz
}

func (q *Queries) InsertProjectFingerprint(ctx context.Context, arg InsertProjectFingerprintParams) (ProjectFingerprint, error) {
	row := q.db.QueryRow(ctx, insertProjectFingerprint,
		arg.ProjectID,
		arg.SchemaVersion,
		arg.FingerprintSha256,
		arg.FingerprintJson,
		arg.SourceRevision,
		arg.ObservedAt,
	)
	var i ProjectFingerprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SchemaVersion,
		&i.FingerprintSha256,
		&i.FingerprintJson,
		&i.SourceRevision,
		&i.ObservedAt,
	)
	return i, err
}

const insertProjectPreference = `-- name: InsertProjectPreference :one
INSERT INTO project_preferences
    (project_id, kind, primitive_id, candidate_id, text_value, int_value,
     source_reason, source_resolution_id, recorded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, kind, primitive_id, candidate_id, text_value, int_value, source_reason, source_resolution_id, recorded_at, forgotten_at
`

type InsertProjectPreferenceParams struct {
	ProjectID          string
	Kind               string
	PrimitiveID        string
	CandidateID        string
	TextValue          string
	IntValue           *int32
	SourceReason       string
	SourceResolutionID *int64
	RecordedAt         pgtype.Timestamptz
}

func (q *Queries) InsertProjectPreference(ctx context.Context, arg InsertProjectPreferenceParams) (ProjectPreference, error) {
	row := q.db.QueryRow(ctx, insertProjectPreference,
		arg.ProjectID,
		arg.Kind,
		arg.PrimitiveID,
		arg.CandidateID,
		arg.TextValue,
		arg.IntValue,
		arg.SourceReason,
		arg.SourceResolutionID,
		arg.RecordedAt,
	)
	var i ProjectPreference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.PrimitiveID,
		&i.CandidateID,
		&i.TextValue,
		&i.IntValue,
		&i.SourceReason,
		&i.SourceResolutionID,
		&i.RecordedAt,
		&i.ForgottenAt,
	)
	return i, err
}

const listActiveProjectPreferences = `-- name: ListActiveProjectPreferences :many
SELECT id, project_id, kind, primitive_id, candidate_id, text_value, int_value, source_reason, source_resolution_id, recorded_at, forgotten_at
FROM project_preferences
WHERE project_id = $1
  AND forgotten_at IS NULL
ORDER BY id
LIMIT $2
`

type ListActiveProjectPreferencesParams struct {
	ProjectID string
	Limit     int32
}

func (q *Queries) ListActiveProjectPreferences(ctx context.Context, arg ListActiveProjectPreferencesParams) ([]ProjectPreference, error) {
	rows, err := q.db.Query(ctx, listActiveProjectPreferences, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectPreference{}
	for rows.Next() {
		var i ProjectPreference
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.PrimitiveID,
			&i.CandidateID,
			&i.TextValue,
			&i.IntValue,
			&i.SourceReason,
			&i.SourceResolutionID,
			&i.RecordedAt,
			&i.ForgottenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPreferences = `-- name: ListProjectPreferences :many
SELECT id, project_id, kind, primitive_id, candidate_id, text_value, int_value, source_reason, source_resolution_id, recorded_at, forgotten_at
FROM project_preferences
WHERE project_id = $1
ORDER BY id
LIMIT $2
`

type ListProjectPreferencesParams struct {
	ProjectID string
	Limit     int32
}

func (q *Queries) ListProjectPreferences(ctx context.Context, arg ListProjectPreferencesParams) ([]ProjectPreference, error) {
	rows, err := q.db.Query(ctx, listProjectPreferences, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectPreference{}
	for rows.Next() {
		var i ProjectPreference
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.PrimitiveID,
			&i.CandidateID,
			&i.TextValue,
			&i.IntValue,
			&i.SourceReason,
			&i.SourceResolutionID,
			&i.RecordedAt,
			&i.ForgottenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolutionsByProject = `-- name: ListResolutionsByProject :many
SELECT id, primitive_id, contract_id, outcome, specimen_id, reasons, unknowns, evidence_ids, resolved_at, policy_id, project_id, project_context_hash
FROM resolutions
WHERE project_id = $1
ORDER BY resolved_at DESC, id DESC
LIMIT $2
`

type ListResolutionsByProjectParams struct {
	ProjectID *string
	Limit     int32
}

func (q *Queries) ListResolutionsByProject(ctx context.Context, arg ListResolutionsByProjectParams) ([]Resolution, error) {
	rows, err := q.db.Query(ctx, listResolutionsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resolution{}
	for rows.Next() {
		var i Resolution
		if err := rows.Scan(
			&i.ID,
			&i.PrimitiveID,
			&i.ContractID,
			&i.Outcome,
			&i.SpecimenID,
			&i.Reasons,
			&i.Unknowns,
			&i.EvidenceIds,
			&i.ResolvedAt,
			&i.PolicyID,
			&i.ProjectID,
			&i.ProjectContextHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (id, name, source_kind, source_locator, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT (id) DO UPDATE
SET name           = EXCLUDED.name,
    source_kind    = EXCLUDED.source_kind,
    source_locator = EXCLUDED.source_locator,
    updated_at     = EXCLUDED.updated_at
RETURNING id, name, source_kind, source_locator, created_at, updated_at
`

type UpsertProjectParams struct {
	ID            string
	Name          string
	SourceKind    string
	SourceLocator string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.ID,
		arg.Name,
		arg.SourceKind,
		arg.SourceLocator,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceKind,
		&i.SourceLocator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectContext = `-- name: UpsertProjectContext :one
INSERT INTO project_contexts (hash, project_id, fingerprint_id, context_json, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (hash) DO UPDATE
SET project_id     = EXCLUDED.project_id,
    fingerprint_id = EXCLUDED.fingerprint_id,
    context_json   = EXCLUDED.context_json
RETURNING hash, project_id, fingerprint_id, context_json, created_at
`

type UpsertProjectContextParams struct {
	Hash          string
	ProjectID     string
	FingerprintID int64
	ContextJson   []byte
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) UpsertProjectContext(ctx context.Context, arg UpsertProjectContextParams) (ProjectContext, error) {
	row := q.db.QueryRow(ctx, upsertProjectContext,
		arg.Hash,
		arg.ProjectID,
		arg.FingerprintID,
		arg.ContextJson,
		arg.CreatedAt,
	)
	var i ProjectContext
	err := row.Scan(
		&i.Hash,
		&i.ProjectID,
		&i.FingerprintID,
		&i.ContextJson,
		&i.CreatedAt,
	)
	return i, err
}
