// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resolutions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countResolutions = `-- name: CountResolutions :one
SELECT COUNT(*)
FROM resolutions
`

func (q *Queries) CountResolutions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countResolutions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getResolution = `-- name: GetResolution :one
SELECT id, primitive_id, contract_id, outcome, specimen_id, reasons, unknowns, evidence_ids, resolved_at, policy_id
FROM resolutions
WHERE id = $1
`

func (q *Queries) GetResolution(ctx context.Context, id int64) (Resolution, error) {
	row := q.db.QueryRow(ctx, getResolution, id)
	var i Resolution
	err := row.Scan(
		&i.ID,
		&i.PrimitiveID,
		&i.ContractID,
		&i.Outcome,
		&i.SpecimenID,
		&i.Reasons,
		&i.Unknowns,
		&i.EvidenceIds,
		&i.ResolvedAt,
		&i.PolicyID,
	)
	return i, err
}

const insertRejection = `-- name: InsertRejection :exec
INSERT INTO rejections (resolution_id, position, specimen_id, reasons)
VALUES ($1, $2, $3, $4)
`

type InsertRejectionParams struct {
	ResolutionID int64
	Position     int32
	SpecimenID   string
	Reasons      []string
}

func (q *Queries) InsertRejection(ctx context.Context, arg InsertRejectionParams) error {
	_, err := q.db.Exec(ctx, insertRejection,
		arg.ResolutionID,
		arg.Position,
		arg.SpecimenID,
		arg.Reasons,
	)
	return err
}

const insertResolution = `-- name: InsertResolution :one
INSERT INTO resolutions (primitive_id, contract_id, outcome, specimen_id, reasons, unknowns, evidence_ids, policy_id, resolved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, primitive_id, contract_id, outcome, specimen_id, reasons, unknowns, evidence_ids, resolved_at, policy_id
`

type InsertResolutionParams struct {
	PrimitiveID string
	ContractID  string
	Outcome     string
	SpecimenID  *string
	Reasons     []string
	Unknowns    []string
	EvidenceIds []string
	PolicyID    string
	ResolvedAt  pgtype.Timestamptz
}

func (q *Queries) InsertResolution(ctx context.Context, arg InsertResolutionParams) (Resolution, error) {
	row := q.db.QueryRow(ctx, insertResolution,
		arg.PrimitiveID,
		arg.ContractID,
		arg.Outcome,
		arg.SpecimenID,
		arg.Reasons,
		arg.Unknowns,
		arg.EvidenceIds,
		arg.PolicyID,
		arg.ResolvedAt,
	)
	var i Resolution
	err := row.Scan(
		&i.ID,
		&i.PrimitiveID,
		&i.ContractID,
		&i.Outcome,
		&i.SpecimenID,
		&i.Reasons,
		&i.Unknowns,
		&i.EvidenceIds,
		&i.ResolvedAt,
		&i.PolicyID,
	)
	return i, err
}

const listRejectionsByResolution = `-- name: ListRejectionsByResolution :many
SELECT resolution_id, position, specimen_id, reasons
FROM rejections
WHERE resolution_id = $1
ORDER BY position
`

func (q *Queries) ListRejectionsByResolution(ctx context.Context, resolutionID int64) ([]Rejection, error) {
	rows, err := q.db.Query(ctx, listRejectionsByResolution, resolutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rejection{}
	for rows.Next() {
		var i Rejection
		if err := rows.Scan(
			&i.ResolutionID,
			&i.Position,
			&i.SpecimenID,
			&i.Reasons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
