// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: specimens.sql

package sqlc

import (
	"context"
)

const getSpecimen = `-- name: GetSpecimen :one
SELECT id, primitive_id, name, source_url, source_revision, source_path, source_license, reuse_modes
FROM specimens
WHERE id = $1
`

func (q *Queries) GetSpecimen(ctx context.Context, id string) (Specimen, error) {
	row := q.db.QueryRow(ctx, getSpecimen, id)
	var i Specimen
	err := row.Scan(
		&i.ID,
		&i.PrimitiveID,
		&i.Name,
		&i.SourceUrl,
		&i.SourceRevision,
		&i.SourcePath,
		&i.SourceLicense,
		&i.ReuseModes,
	)
	return i, err
}

const upsertSpecimen = `-- name: UpsertSpecimen :one
INSERT INTO specimens (id, primitive_id, name, source_url, source_revision, source_path, source_license, reuse_modes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET primitive_id    = EXCLUDED.primitive_id,
    name            = EXCLUDED.name,
    source_url      = EXCLUDED.source_url,
    source_revision = EXCLUDED.source_revision,
    source_path     = EXCLUDED.source_path,
    source_license  = EXCLUDED.source_license,
    reuse_modes     = EXCLUDED.reuse_modes
RETURNING id, primitive_id, name, source_url, source_revision, source_path, source_license, reuse_modes
`

type UpsertSpecimenParams struct {
	ID             string
	PrimitiveID    string
	Name           string
	SourceUrl      string
	SourceRevision string
	SourcePath     string
	SourceLicense  string
	ReuseModes     []string
}

func (q *Queries) UpsertSpecimen(ctx context.Context, arg UpsertSpecimenParams) (Specimen, error) {
	row := q.db.QueryRow(ctx, upsertSpecimen,
		arg.ID,
		arg.PrimitiveID,
		arg.Name,
		arg.SourceUrl,
		arg.SourceRevision,
		arg.SourcePath,
		arg.SourceLicense,
		arg.ReuseModes,
	)
	var i Specimen
	err := row.Scan(
		&i.ID,
		&i.PrimitiveID,
		&i.Name,
		&i.SourceUrl,
		&i.SourceRevision,
		&i.SourcePath,
		&i.SourceLicense,
		&i.ReuseModes,
	)
	return i, err
}
