// Package postgres implements Reusery's PostgreSQL persistence.
//
// It is deliberately the only storage backend for now. SQL is generated by
// sqlc from authored queries and mapped by hand to internal/model; generated
// database structs never escape this package.
package postgres

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// connectTimeout bounds the initial connectivity check performed by Open.
const connectTimeout = 10 * time.Second

// readyTimeout bounds each readiness probe.
const readyTimeout = 2 * time.Second

// Open parses databaseURL, creates a pgxpool using pgx defaults and verifies
// connectivity with a bounded ping. The caller owns the returned pool and must
// Close it during shutdown.
func Open(ctx context.Context, databaseURL string) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(databaseURL)
	if err != nil {
		return nil, fmt.Errorf("parse database URL: %w", err)
	}

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("create pool: %w", err)
	}

	pingCtx, cancel := context.WithTimeout(ctx, connectTimeout)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("connect to postgres: %w", err)
	}
	return pool, nil
}

// ReadyChecker returns a readiness function compatible with
// server.ReadyChecker. It pings the pool and fails when PostgreSQL is
// unavailable.
func ReadyChecker(pool *pgxpool.Pool) func(context.Context) error {
	return func(ctx context.Context) error {
		pingCtx, cancel := context.WithTimeout(ctx, readyTimeout)
		defer cancel()
		return pool.Ping(pingCtx)
	}
}
